# -------------- in-memory database configurations ------------------

#spring:
#  app:
#    name: Spring Security Services
#    version: 1.0.1
#
#  datasource:
#    url: jdbc:h2:mem:example
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#
#  h2:
#    console:
#      enabled: true
#      path: /h2
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#  output:
#    ansi:
#      enabled: ALWAYS
#
#server:
#  port: 8080
#

